name: "Helm Chart Release"

on:
  push: {}
  workflow_dispatch: {}

jobs:
  helm-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "<41898282+github-actions[bot]@users.noreply.github.com>"
      - name: Release Kuma chart
        uses: helm/chart-releaser-action@v1.3.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: deployments/charts
            #charts_repo_url: https://michaelbeaumont.github.io/charts
