name: "Helm Charts"

on:
  push: {}
  workflow_dispatch: {}

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    outputs:
      filename: ${{ steps.package.outputs.filename }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install chart-releaser
        run: |
          VER="1.3.0"
          curl -L -o /tmp/cr-${VER}.tgz https://github.com/helm/chart-releaser/releases/download/v${VER}/chart-releaser_${VER}_linux_amd64.tar.gz
          mkdir -p /tmp/cr
          tar -xz -C /tmp/cr -f /tmp/cr-$VER.tgz
          sudo mv /tmp/cr/cr /usr/bin
      - name: Package helm chart
        id: package
        run: |
          ./tools/releases/helm.sh --package
          VER=$(find .cr-release-packages -type f -printf "%f\n")
          echo "::set-output name=filename::${VER}"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.package.outputs.filename }}
          path: .cr-release-packages/${{ steps.package.outputs.filename }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: package
    if: github.event == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "<41898282+github-actions[bot]@users.noreply.github.com>"
      - name: Install chart-releaser
        run: |
          VER="1.3.0"
          curl -L -o /tmp/cr-${VER}.tgz https://github.com/helm/chart-releaser/releases/download/v${VER}/chart-releaser_${VER}_linux_amd64.tar.gz
          mkdir -p /tmp/cr
          tar -xz -C /tmp/cr -f /tmp/cr-$VER.tgz
          sudo mv /tmp/cr/cr /usr/bin
      - uses: actions/download-artifact@v2
        with:
          name: ${{ needs.package.outputs.filename }}
          path: .cr-release-packages/${{ needs.package.outputs.filename }}
      - name: Release helm chart
        env:
          CR_SKIP_EXISTING: "true"
          GH_OWNER: michaelbeaumont
        run: |
          ./tools/releases/helm.sh --release
