name: "Notify on merged PR"

on:
  pull_request:
    types: [closed]
    branches:
    - master
  workflow_dispatch:

jobs:
  if: github.event.pull_request.merged
  notify-about-merge:
    runs-on: ubuntu-latest
    steps:
    - name: "Notify other repositories about push to master"
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.NOTIFY_GH_TOKEN }}
        script: |
          return github.rest.repos.createDispatchEvent({
            owner: '${{ secrets.NOTIFY_OWNER }}',
            repo: '${{ secrets.NOTIFY_REPO }}',
            event_type: '${{ secrets.NOTIFY_EVENT_TYPE }}',
            client_payload: {
              pr: ${{ github.event.pull_request.number}},
            },
          });
